version: '3.1'

services:
    ddb_local:
        image: cnadiminti/dynamodb-local:latest
        ports:
            - 8000:8000
        volumes:
            - ./dynamodb-docker-data:/dynamodb_local_db